### ISSUE TITLE
genParams is not defined

### ISSUE THREAD

**Issue by relin-merlux** [lpg2709/clickup_api#1]
I got follow this error, when run get_tasks.js , get_team_tasks.js .

**ReferenceError: genParams is not defined
    at E:\nodeproject\clickup_api-master\src\components\Tasks.js:76:16
    at new Promise (<anonymous>)
    at Tasks.get_tasks (E:\nodeproject\clickup_api-master\src\components\Tasks.js:74:9)
    at main (E:\nodeproject\clickup_api-master\testes\Tasks\get_tasks.js:27:34)
    at Object.<anonymous> (E:\nodeproject\clickup_api-master\testes\Tasks\get_tasks.js:35:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)**

But  get_task.js is working fine .

**Comment by lpg2709** [comment]
Hey dude, i'm gonna see that. 
Thanks for reporting.

**Comment by lpg2709** [comment]
Fixed.
